### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by donhausk** [TuringLang/AdvancedPS.jl#1]
Implementation:
- [x] Implement PG and SMC
- [] Implement PGAS
- [] Write Interface for package with additional functionalities

Testing:
- [] Test PG and SMC
- [] Test PG and SMC in combination with Turing branch ParticleGibbsExtension
- [] Test PGAS
- [] Test PGAS in combination with Turing branch ParticleGibbsExtension
